# Generated by Django 5.1.4 on 2025-04-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="catagory",
        ),
    ]
