# Generated by Django 5.1.4 on 2025-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_catagory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[("P", "Processing"), ("S", "Shipped"), ("D", "Delivered")],
                default="P",
                max_length=1,
            ),
        ),
    ]
