# Generated by Django 5.1.4 on 2025-05-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.type",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="catagory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                to="api.catagory",
            ),
        ),
    ]
